uint8 MOTOR_1=1
uint8 MOTOR_2=2
uint8 MOTOR_3=4
uint8 MOTOR_4=8
uint8 ALL_MOTORS=15

uint8 update_mask
float32[4] input_gain_rps_per_second_per_permille
float32[4] controller_bandwidth_rad_s
float32[4] observer_bandwidth_rad_s
float32[4] velocity_filter_new_weight
---
mentor_pi_interfaces/Result result
uint8 applied_mask
