/**:
  ros__parameters:
    vehicle_type: mecanum
    tracking_algorithm: adrc
    controller_plugin: mentor_pi_tracking/MecanumAdrc
    horizon: 10
    prediction_step: 0.1
    wheelbase: 0.135
    wheel_track: 0.140
    rear_axle_to_geometry_center: 0.0675
    wheel_radius: 0.0325
    driven_wheel_angular_speed_limit_rad_s: 37.69911184307752
    mecanum_radius_sum: 0.14
    max_steering_angle: 0.6
    position_adrc_input_gain: 1.0
    position_adrc_controller_bandwidth_rad_s: 1.0
    position_adrc_observer_bandwidth_rad_s: 3.0
    yaw_adrc_input_gain: 1.0
    yaw_adrc_controller_bandwidth_rad_s: 1.0
    yaw_adrc_observer_bandwidth_rad_s: 3.0
