uint8 MOTOR_1=1
uint8 MOTOR_2=2
uint8 MOTOR_3=4
uint8 MOTOR_4=8
uint8 ALL_MOTORS=15

uint8 update_mask
float32[4] proportional_gain
float32[4] integral_gain
float32[4] derivative_gain
float32[4] velocity_filter_new_weight
---
mentor_pi_interfaces/Result result
uint8 applied_mask
