export ZSH="${HOME}/.oh-my-zsh"
export HISTFILE="${HOME}/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000

ZSH_THEME="robbyrussell"
plugins=(
  git
  sudo
  zsh-autosuggestions
  zsh-syntax-highlighting
)

# Load the ROS underlay and the micro-ROS builder overlay before Oh My Zsh
# initializes completion. Both setup files are part of the Dev Container.
source /opt/ros/humble/setup.zsh
source /uros_ws/install/setup.zsh
source "${ZSH}/oh-my-zsh.sh"

setopt append_history
setopt hist_ignore_dups
setopt hist_reduce_blanks
setopt nonomatch
setopt share_history
zstyle ':completion:*' menu select
